# Generated by Django 6.1.1 on 2026-09-26 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('candidate', 'Candidate'), ('company', 'Company')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=80)),
                ('skills', models.CharField(blank=True, max_length=300)),
                ('experience_years', models.IntegerField(default=0)),
                ('nationality', models.CharField(blank=True, max_length=60)),
                ('iqama_status', models.CharField(blank=True, max_length=40)),
                ('languages', models.CharField(blank=True, max_length=120)),
                ('expected_salary', models.IntegerField(default=0)),
                ('company_name', models.CharField(blank=True, max_length=120)),
                ('cr_number', models.CharField(blank=True, max_length=30)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('skills', models.CharField(blank=True, max_length=300)),
                ('workers_needed', models.IntegerField(default=1)),
                ('skill_level', models.CharField(default='Skilled', max_length=20)),
                ('min_experience', models.IntegerField(default=0)),
                ('salary_min', models.IntegerField(default=0)),
                ('salary_max', models.IntegerField(default=0)),
                ('contract_type', models.CharField(default='Monthly', max_length=20)),
                ('location', models.CharField(blank=True, max_length=80)),
                ('duty_hours', models.IntegerField(default=8)),
                ('auto_reject', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview scheduled'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('match_score', models.IntegerField(default=0)),
                ('interview_at', models.DateTimeField(blank=True, null=True)),
                ('interview_mode', models.CharField(blank=True, max_length=20)),
                ('offer_status', models.CharField(default='none', max_length=10)),
                ('offer_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.job')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
